<?php
$app=require dirname(__DIR__).'/config/app.php';
$seo=$seo??['title'=>$app['title'],'description'=>$app['description'],'path'=>current_path(),'type'=>'website'];
$plain=static fn(string $value):string=>html_entity_decode(strip_tags($value),ENT_QUOTES|ENT_HTML5,'UTF-8');
$canonical=rtrim($app['base_url'],'/').$seo['path'];
$siteUrl=rtrim($app['base_url'],'/');
$organization=['@context'=>'https://schema.org','@type'=>'Organization','@id'=>$siteUrl.'/#organization','name'=>'Metal Life','alternateName'=>'Metal Life Industrial','url'=>$siteUrl.'/','logo'=>['@type'=>'ImageObject','url'=>$siteUrl.'/img/metal-life-logo.png','width'=>1200,'height'=>1200],'description'=>$plain('Fabricante de caixas met&aacute;licas, gabinetes, quadros el&eacute;tricos e cabines de pintura industrial sob medida.'),'email'=>'contato@metallife.com.br','telephone'=>'+55 11 96919-5102','sameAs'=>['https://www.instagram.com/mettal.life/']];
$website=['@context'=>'https://schema.org','@type'=>'WebSite','@id'=>$siteUrl.'/#website','url'=>$siteUrl.'/','name'=>'Metal Life','alternateName'=>['Metal Life Industrial','metallife.com.br'],'publisher'=>['@id'=>$siteUrl.'/#organization'],'inLanguage'=>'pt-BR'];
?>
<!doctype html><html lang="pt-BR"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?=e($plain($seo['title']))?></title><meta name="description" content="<?=e($plain($seo['description']))?>">
<link rel="canonical" href="<?=e($canonical)?>"><meta name="robots" content="index,follow,max-image-preview:large">
<meta name="theme-color" content="#102b46"><meta property="og:locale" content="pt_BR"><meta property="og:type" content="<?=e($seo['type'])?>"><meta property="og:site_name" content="Metal Life"><meta property="og:title" content="<?=e($plain($seo['title']))?>"><meta property="og:description" content="<?=e($plain($seo['description']))?>"><meta property="og:url" content="<?=e($canonical)?>"><meta property="og:image" content="<?=e(rtrim($app['base_url'],'/').'/images/cabines-pintura/cabine-pintura-eletrostatica-po.jpg')?>">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="<?=e($plain($seo['title']))?>"><meta name="twitter:description" content="<?=e($plain($seo['description']))?>">
<link rel="icon" href="/favicon.png?v=3" type="image/png"><link rel="apple-touch-icon" href="/favicon.png?v=3"><link rel="manifest" href="/manifest.json?v=3"><link rel="stylesheet" href="/assets/css/site.css?v=27">
<script type="application/ld+json" nonce="<?=e($cspNonce)?>"><?=json_encode($organization,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script>
<?php if($seo['path']==='/'):?><script type="application/ld+json" nonce="<?=e($cspNonce)?>"><?=json_encode($website,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script><?php endif;?>
</head><body>
<a class="skip-link" href="#main-content">Pular para o conte&uacute;do</a>
<header class="site-header"><div class="header-inner">
 <a class="site-logo" href="/" aria-label="Metal Life &mdash; p&aacute;gina inicial"><img src="/img/metal-life-logo.png" width="62" height="62" alt="Metal Life"></a>
 <nav class="desktop-nav" aria-label="Navega&ccedil;&atilde;o principal">
  <a class="<?=e(active_path('/'))?>" href="/">In&iacute;cio</a>
  <a class="<?=e(active_path('/empresa'))?>" href="/empresa">A Metal Life</a>
  <div class="nav-group <?=str_contains(current_path(),'caixa')||str_contains(current_path(),'quadro')||str_contains(current_path(),'gabinete')?'active':''?>"><button type="button" aria-expanded="false">Caixas e pain&eacute;is <span aria-hidden="true">+</span></button><div class="nav-dropdown"><a href="/caixas-metalicas-paineis-eletricos">Vis&atilde;o geral</a><a href="/caixa-metalica-sobrepor">Caixas de sobrepor</a><a href="/caixa-metalica-embutir">Caixas de embutir</a><a href="/quadros-comando-metalicos">Quadros de comando</a><a href="/gabinetes-autoportantes">Gabinetes autoportantes</a><a href="/caixas-passagem-metalicas">Caixas de passagem</a><a href="/caixas-metalicas-ip54-ip65">Caixas IP54 e IP65</a></div></div>
  <div class="nav-group <?=str_contains(current_path(),'cabine')||str_contains(current_path(),'estufa')?'active':''?>"><button type="button" aria-expanded="false">Cabines de pintura <span aria-hidden="true">+</span></button><div class="nav-dropdown"><a href="/cabines-pintura-industrial">Vis&atilde;o geral</a><a href="/cabine-pintura-eletrostatica-po">Pintura eletrost&aacute;tica a p&oacute;</a><a href="/cabine-pintura-liquida">Pintura l&iacute;quida</a><a href="/cabine-pintura-automatica">Cabines autom&aacute;ticas</a><a href="/estufas-fornos-cura">Estufas e fornos</a></div></div>
  <a class="<?=e(active_path('/aplicacoes-setores'))?>" href="/aplicacoes-setores">Aplica&ccedil;&otilde;es</a>
  <a class="<?=e(is_path_prefix('/conteudo-tecnico'))?>" href="/conteudo-tecnico">Conte&uacute;do</a>
  <a class="<?=e(active_path('/contato'))?>" href="/contato">Contato</a>
 </nav>
 <a class="header-quote" href="https://wa.me/5511969195102" target="_blank" rel="noopener noreferrer"><span>Solicitar or&ccedil;amento</span><strong aria-hidden="true">&rarr;</strong></a>
 <button class="menu-trigger" type="button" data-menu-open aria-controls="mobile-menu" aria-expanded="false"><span>Menu</span><b aria-hidden="true"></b></button>
</div></header>
<div class="mobile-menu" id="mobile-menu" data-mobile-menu hidden><div class="mobile-menu-head"><img src="/img/metal-life-logo.png" width="62" height="62" alt="Metal Life"><button type="button" data-menu-close>Fechar</button></div><nav aria-label="Menu mobile"><a href="/">In&iacute;cio</a><a href="/empresa">A Metal Life</a><a href="/caixas-metalicas-paineis-eletricos">Caixas e pain&eacute;is</a><a href="/cabines-pintura-industrial">Cabines de pintura</a><a href="/aplicacoes-setores">Aplica&ccedil;&otilde;es</a><a href="/conteudo-tecnico">Conte&uacute;do t&eacute;cnico</a><a href="/contato">Contato</a><a class="mobile-quote" href="https://wa.me/5511969195102" target="_blank" rel="noopener noreferrer">Solicitar or&ccedil;amento <span aria-hidden="true">&rarr;</span></a></nav></div>
<main id="main-content" tabindex="-1"><?php require __DIR__.'/'.$template.'.php';?></main>
<footer class="site-footer"><div class="footer-grid"><div class="footer-brand"><img src="/img/metal-life-logo.png" width="150" height="150" alt="Metal Life"><p>Solu&ccedil;&otilde;es met&aacute;licas e equipamentos desenvolvidos para necessidades reais da ind&uacute;stria.</p></div><nav aria-label="Produtos"><strong>Produtos</strong><a href="/caixas-metalicas-paineis-eletricos">Caixas e pain&eacute;is</a><a href="/cabines-pintura-industrial">Cabines de pintura</a><a href="/estufas-fornos-cura">Estufas e fornos</a><a href="https://wa.me/5511969195102" target="_blank" rel="noopener noreferrer">Solicitar or&ccedil;amento</a></nav><nav aria-label="Institucional"><strong>Metal Life</strong><a href="/empresa">A empresa</a><a href="/aplicacoes-setores">Aplica&ccedil;&otilde;es</a><a href="/conteudo-tecnico">Conte&uacute;do t&eacute;cnico</a><a href="/contato">Contato</a></nav><section class="footer-contact-panel" aria-labelledby="footer-contact-title"><span class="footer-contact-kicker">Atendimento direto</span><h2 id="footer-contact-title">Seu projeto come&ccedil;a com uma conversa.</h2><a class="footer-contact-number" href="tel:+5511969195102"><small>Telefone comercial</small><strong>+55 11 96919-5102</strong></a><div class="footer-contact-emails"><a href="mailto:comercial@metallife.com.br"><small>Comercial</small><strong>comercial@metallife.com.br</strong></a><a href="mailto:contato@metallife.com.br"><small>Contato</small><strong>contato@metallife.com.br</strong></a></div><div class="footer-social-actions"><a class="footer-social footer-social-whatsapp" href="https://wa.me/5511969195102" target="_blank" rel="noopener noreferrer" aria-label="Conversar com a Metal Life pelo WhatsApp" title="WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.8a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.3-4.7a8.5 8.5 0 1 1 16.2-4z"/><path d="M8.2 7.6c.2-.4.4-.4.7-.4h.4c.2 0 .4.1.5.4l.8 1.8c.1.3.1.5-.1.7l-.6.7c-.2.2-.2.4 0 .6.5.9 1.2 1.6 2 2.1.3.2.4.2.7 0l.8-.9c.2-.2.4-.3.7-.2l1.8.8c.3.1.4.3.4.5 0 .5-.2 1.3-.7 1.8-.5.5-1.2.8-2 .8-1 0-2.6-.6-4.3-2.1-1.9-1.7-3.2-3.9-3.2-5.3 0-.6.2-1 .3-1.3z"/></svg></a><a class="footer-social footer-social-instagram" href="https://www.instagram.com/mettal.life/" target="_blank" rel="noopener noreferrer" aria-label="Visitar o Instagram da Metal Life" title="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.7" r="1"/></svg></a></div></section></div><div class="footer-bottom"><span>&copy; <?=date('Y')?> Metal Life. Todos os direitos reservados.</span><a href="/politica-de-privacidade">Pol&iacute;tica de Privacidade</a></div></footer>
<script src="/assets/js/site.js?v=4" defer></script></body></html>
