<?php $items=[['label'=>'In&iacute;cio','url'=>'/'],['label'=>'Solicitar or&ccedil;amento','url'=>null]];require __DIR__.'/partials/breadcrumb.php';$d=$formData??[];$selected=$d['interest']??($_GET['produto']??'');?>
<section class="quote-layout wrap"><div class="quote-intro"><span class="eyebrow">Atendimento comercial</span><h1>Solicite um or&ccedil;amento para o seu projeto</h1><p>Envie as informa&ccedil;&otilde;es dispon&iacute;veis. Medidas aproximadas, fotos e desenhos ajudam a equipe a compreender a aplica&ccedil;&atilde;o antes do contato.</p><ol><li><strong>Descreva a necessidade</strong><span>Produto, processo, quantidade e medidas.</span></li><li><strong>Anexe uma refer&ecirc;ncia</strong><span>PDF, imagem ou desenho, se houver.</span></li><li><strong>Aguarde a avalia&ccedil;&atilde;o</strong><span>Os dados ficam registrados para contato comercial.</span></li></ol></div><div class="form-panel">
<?php if(($formStatus??null)==='success'):?><div class="form-notice success" role="status" tabindex="-1" data-focus-notice><strong>Solicita&ccedil;&atilde;o recebida.</strong><p>As informa&ccedil;&otilde;es foram registradas para avalia&ccedil;&atilde;o comercial.</p></div><?php endif;?>
<?php if(!empty($formErrors)):?><div class="form-notice error" role="alert"><strong>Revise o formul&aacute;rio:</strong><ul><?php foreach($formErrors as $error):?><li><?=$error?></li><?php endforeach;?></ul></div><?php endif;?>
<form class="quote-form" method="post" action="/solicitar-orcamento" enctype="multipart/form-data" data-submit-form><input type="hidden" name="csrf" value="<?=e($csrf)?>"><input type="hidden" name="origin" value="<?=e($d['origin']??($_SERVER['HTTP_REFERER']??current_path()))?>"><label class="honeypot" aria-hidden="true">N&atilde;o preencher<input type="text" name="website" tabindex="-1" autocomplete="off"></label>
<div class="form-row"><label>Nome completo <span>*</span><input type="text" name="name" value="<?=e($d['name']??'')?>" autocomplete="name" maxlength="120" required></label><label>Empresa <span>*</span><input type="text" name="company" value="<?=e($d['company']??'')?>" autocomplete="organization" maxlength="160" required></label></div>
<div class="form-row"><label>E-mail <span>*</span><input type="email" name="email" value="<?=e($d['email']??'')?>" autocomplete="email" maxlength="254" required></label><label>Telefone <span>*</span><input type="tel" name="phone" value="<?=e($d['phone']??'')?>" autocomplete="tel" maxlength="40" required></label></div>
<label>Cidade e estado<input type="text" name="location" value="<?=e($d['location']??'')?>" autocomplete="address-level2" maxlength="160"></label>
<label>Produto de interesse <span>*</span><select name="interest" required><option value="">Selecione</option><?php foreach(['Caixa met&aacute;lica para painel el&eacute;trico','Quadro de comando met&aacute;lico','Gabinete autoportante','Caixa de passagem','Caixa sob medida','Cabine de pintura eletrost&aacute;tica','Cabine de pintura l&iacute;quida','Cabine autom&aacute;tica','Estufa ou forno de cura','Outro'] as $opt):?><option value="<?=e($opt)?>" <?=($selected===$opt?'selected':'')?>><?=$opt?></option><?php endforeach;?></select></label>
<div class="form-row"><label>Tipo de aplica&ccedil;&atilde;o<input type="text" name="application" value="<?=e($d['application']??'')?>" maxlength="300"></label><label>Medidas aproximadas<input type="text" name="dimensions" value="<?=e($d['dimensions']??'')?>" maxlength="160" placeholder="Ex.: largura &times; altura &times; profundidade"></label></div>
<div class="form-row"><label>Quantidade<input type="number" min="1" max="999999" name="quantity" value="<?=e($d['quantity']??'')?>"></label><label>Grau de prote&ccedil;&atilde;o, se aplic&aacute;vel<select name="protection"><option value="">A definir</option><option <?=($d['protection']??'')==='IP54'?'selected':''?>>IP54</option><option <?=($d['protection']??'')==='IP65'?'selected':''?>>IP65</option><option <?=($d['protection']??'')==='Outro / sob avalia&ccedil;&atilde;o'?'selected':''?>>Outro / sob avalia&ccedil;&atilde;o</option></select></label></div>
<label>Mensagem <span>*</span><textarea name="message" rows="6" maxlength="4000" required placeholder="Descreva a aplica&ccedil;&atilde;o, ambiente, prazo e requisitos conhecidos."><?=e($d['message']??'')?></textarea></label>
<label class="file-field">Anexar desenho, projeto ou imagem <small>PDF, JPG, PNG ou WebP, at&eacute; 5 MB.</small><input type="file" name="project_file" accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp"></label>
<label class="consent"><input type="checkbox" name="consent" value="1" required><span>Li e concordo com a <a href="/politica-de-privacidade" target="_blank">Pol&iacute;tica de Privacidade</a>. *</span></label>
<button class="button button-primary" type="submit" data-submit-button>Enviar solicita&ccedil;&atilde;o</button></form></div></section>
